language: ruby
rvm:
- 2.6.1



before_install:
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER appv2 WITH PASSWORD 'password1';" -U postgres
  - cp config/database.yml.travis config/database.yml

services:
  - postgresql